name: to_do_list
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_slidable: ^1.2.0
  shared_preferences: ^2.0.13
  file_picker: ^5.2.11
  image_picker: ^0.8.7+4
  firebase_core: ^2.10.0
  firebase_storage: ^11.1.1
  carousel_slider: ^4.2.1
  sqflite: ^2.2.7
  video_player: ^2.6.1
  http: ^0.13.5
  firebase_messaging: ^14.4.1
  simple_animations: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

assets:
   - assets/images/

flutter:
  uses-material-design: true


